logging:
  path: /data/logs/app_logs
  file: smt-goods
  config: classpath:logback.xml

server:
  port: 8083
  context-path: /
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    type: "com.alibaba.druid.pool.DruidDataSource"
    url: "jdbc:mysql://localhost:3306/test?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8"
    username: "root"
    password: "123456"
    driver-class-name: "com.mysql.jdbc.Driver"
    # 数据库连接池配置
    filters: stat,wall,log4j
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    dbcp2:
      # 当连接池被启动时初始化创建的连接个数
      initial-size: 50
      # 可以在连接池中保持空闲的最大连接数，超出设置值之外的空闲连接将被回收，如设置为负数，则不限制
      max-idle: 50
      # 可以在连接池中保持空闲的最小连接数，超出设置值之外的空闲连接将被创建，如设置为0，则不创建
      min-idle: 100
      # 可以在连接池中同时被分配的有效连接数的最大值，如设置为负数，则不限制
      max-total: 600
      # （如果没有可用连接）连接池在抛出异常前等待的一个连接被归还的最大毫秒数，设置为-1则等待时间不确定
      max-wait-millis: 6000
      # 间隔多久才进行一次检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 6000
      # 一个连接在池中最小空闲时间
      min-evictable-idle-time-millis: 300000
      # 在连接池返回连接给调用者前用来进行连接校验的查询sql。如果指定，则这个查询必须是一个至少返回一行数据的SQL SELECT语句。如果没有指定，则连接将通过调用isValid() 方法进行校验。
      validation-query: SELECT 1 FROM DUAL
      # 指明对象在创建后是否需要被校验，如果对象校验失败，则触发对象创建的租借尝试将失败
      test-on-create: false
      # 指明对象是否需要通过对象驱逐者进行校验（如果有的话），假如一个对象校验失败，则对象将被从池中释放
      test-while-idle: true
      # 指明在从连接池中租借对象时是否要进行校验，如果对象校验失败，则对象将从池子释放，然后将尝试租借另一个
      test-on-borrow: false
      # 指明在将对象归还给连接池前是否需要校验
      test-on-return: false
      # 设置连接池的预处理语句池是否生效
      pool-prepared-statements: true
      # 可以在语句池中同时分配的最大语句数，设置为负数则不限制
      max-open-prepared-statements: 20
      # 一个连接的最大存活毫秒数，如果超过这个时间，则连接在下次激活、钝化、校验时都将会失败。如果设置为0或小于0的值，则连接的存活时间是无限的
      max-conn-lifetime-millis: -1
      #  设置为true表明连接池（如果池中有可用的空闲连接时）将返回最后一次使用的租借对象（最后进入），设置为false则表明池将表现为FIFO队列——将会按照它们被归还的顺序从空闲连接实例池中获取连接
      lifo: false
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
